name: Linters
on:
  pull_request:
    branches:
      - main
      - release/*
    paths-ignore:
      - '**.md'
      - 'docs/mkdocs.yml'
permissions:
  contents: read
jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.19'

      - name: 'Run Linters Aggregator'
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
